name: Child Composite

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
    - uses: Wuodan/ensure-immutable-actions-test-fixtures/composite-actions/leaf@4be2c2d43ede62fdb8eff0be492cd2b6b931bb51
