name: Child Composite

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
    - uses: Wuodan/ensure-immutable-actions-test-custom-actions/composite-actions/leaf@a2c92d755ccc63045b7bb407b26c30965398136c
