name: Nested Immutable Remote Reusable Workflow

on:
  workflow_call:

jobs:
  nested-local-action:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/local-from-nested-workflow

  nested-local-reusable:
    uses: ./.github/workflows/nested-local-child.yml

  nested-remote-reusable:
    uses: Wuodan/ensure-immutable-actions-test-fixtures/.github/workflows/nested-remote-child.yml@<SHA>
