name: Nested Immutable Remote Reusable Workflow

on:
  workflow_call:

jobs:
  nested-local-action:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/local-from-nested-workflow

  nested-local-reusable:
    uses: ./.github/workflows/nested-local-child.yml

  nested-remote-reusable:
    uses: Wuodan/ensure-immutable-actions-test-custom-actions/.github/workflows/nested-remote-child.yml@5c32c76d1aaf7c9a13069971dd2f2eb0c14d75f6
