name: Remote Reusable Workflow Mutable

on:
  workflow_call:

jobs:
  local-from-caller:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/local-from-workflow

  nested-reusable:
    uses: ./.github/workflows/nested-mutable.yml

  remote-nested:
    runs-on: ubuntu-latest
    steps:
      - uses: Wuodan/ensure-immutable-actions-test-fixtures/composite-actions/leaf@981d5959dd308fc885b4f1bbfba9585add12d95c
