name: Remote Reusable Workflow Immutable

on:
  workflow_call:

jobs:
  local-from-caller:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/local-from-workflow

  nested-reusable:
    uses: ./.github/workflows/nested-immutable.yml

  remote-nested:
    runs-on: ubuntu-latest
    steps:
      - uses: Wuodan/ensure-immutable-actions-test-custom-actions/composite-actions/leaf@87788a8bfd15d2098b295b8193e16019bf2e45db
