name: Remote Reusable Workflow

on:
  workflow_call:

jobs:
  local-from-caller:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/local-from-workflow

  remote-nested:
    runs-on: ubuntu-latest
    steps:
      - uses: Wuodan/ensure-immutable-actions-test-custom-actions/composite-actions/leaf@a2c92d755ccc63045b7bb407b26c30965398136c
