name: Remote Reusable Workflow

on:
  workflow_call:

jobs:
  local-from-caller:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/local-from-workflow

  remote-nested:
    runs-on: ubuntu-latest
    steps:
      - uses: Wuodan/ensure-immutable-actions-test-fixtures/composite-actions/leaf@4be2c2d43ede62fdb8eff0be492cd2b6b931bb51
