name: Remote Reusable Workflow Immutable

on:
  workflow_call:

jobs:
  local-from-caller:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/local-from-workflow

  nested-reusable:
    uses: ./.github/workflows/nested-immutable.yml

  remote-nested:
    runs-on: ubuntu-latest
    steps:
      - uses: Wuodan/ensure-immutable-actions-test-fixtures/composite-actions/leaf@9aec95a22c1020150af792e138410a6df2bdc1d1
